kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: boulder-mysql
  namespace: kube-system
  labels:
    k8s-app: boulder-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: boulder-mysql
  template:
    metadata:
      labels:
        k8s-app: boulder-mysql
        name: boulder-mysql
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: boulder-mysql
        image: mariadb:10.1
        args: ["mysqld", "--bind-address=0.0.0.0"]
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - name: tcp
          containerPort: 3306
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
