kind: Service
apiVersion: v1
metadata:
  name: boulder
  namespace: kube-system
spec:
  selector:
    k8s-app: boulder
  ports:
    - protocol: TCP
      port: 4001
      name: http
    - protocol: TCP
      port: 4500
      name: publisher
    - protocol: TCP
      port: 4501
      name: publisher-b
    - protocol: TCP
      port: 4510
      name: publisher-c
    - protocol: TCP
      port: 4511
      name: publisher-d
    - protocol: TCP
      port: 4512
      name: publisher-e
