kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: boulder
  namespace: kube-system
  labels:
    k8s-app: boulder
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: boulder
  template:
    metadata:
      labels:
        k8s-app: boulder
        name: boulder
    spec:
      terminationGracePeriodSeconds: 5
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "sa.boulder"
        - "sa1.boulder"
        - "sa2.boulder"
        - "ca.boulder"
        - "ca1.boulder"
        - "ca2.boulder"
        - "ra.boulder"
        - "ra1.boulder"
        - "ra2.boulder"
        - "va.boulder"
        - "va1.boulder"
        - "va2.boulder"
        - "publisher.boulder"
        - "publisher1.boulder"
        - "publisher2.boulder"
        - "ocsp-updater.boulder"
        - "admin-revoker.boulder"
      initContainers:
        - name: wait-for-boulder-mysql-init
          image: groundnuty/k8s-wait-for:v1.1
          imagePullPolicy: Always
          args: ["pod", "-lname=boulder-mysql"]      
        - name: wait-for-boulder-hsm-init
          image: groundnuty/k8s-wait-for:v1.1
          imagePullPolicy: Always
          args: ["pod", "-lname=boulder-hsm"]      
      containers:
      - name: boulder
        image: dtomcej/boulder:meetup2018-certsadded
        env:
        - name: FAKE_DNS
          value: 10.110.110.110
        - name: PKCS11_PROXY_SOCKET
          value: tcp://boulder-hsm:5657
        - name: BOULDER_CONFIG_DIR
          value: test/config
        ports:
        - containerPort: 4000
        - containerPort: 4001
        readinessProbe:
          httpGet:
            path: /directory
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
